//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventMgmtSystemEntities : DbContext
    {
        public EventMgmtSystemEntities()
            : base("name=EventMgmtSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Info> Employee_Info { get; set; }
        public virtual DbSet<event_attendance_detail> event_attendance_detail { get; set; }
        public virtual DbSet<Event_Info> Event_Info { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
    }
}
