//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contact_Number { get; set; }
        public Nullable<int> User_Type_Id { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
